# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cyber Notebook
email: mmancini@pm.me
description: > # this means to ignore newlines until "baseurl:"
  Personal blog for Marco Mancini. Posts and projects have a focus on
  Cybersecurity, Incident Response , Threat Hunting, Data Analysis and Malware Analysis. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcojmancini.github.io" # the base hostname & protocol for your site
twitter_username: ManciniJ
github_username:  MarcoJMancini

# Build settings
markdown: kramdown
